/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PensionVault } from "./PensionVault";
export * as factories from "./factories";
export { PensionVault__factory } from "./factories/PensionVault__factory";
