/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PensionVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGENCY_WITHDRAWAL_PENALTY"
      | "MAX_EMERGENCY_PERCENTAGE"
      | "RETIREMENT_AGE_SECONDS"
      | "accounts"
      | "addEmployerMatch"
      | "contribute"
      | "emergencyWithdraw"
      | "getAccount"
      | "getContractBalance"
      | "owner"
      | "registerEmployer"
      | "registeredEmployers"
      | "retirementWithdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionMade"
      | "EmergencyWithdrawal"
      | "EmployerMatchAdded"
      | "EmployerRegistered"
      | "RetirementWithdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGENCY_WITHDRAWAL_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EMERGENCY_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RETIREMENT_AGE_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmployerMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerEmployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredEmployers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "retirementWithdraw",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EMERGENCY_WITHDRAWAL_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EMERGENCY_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RETIREMENT_AGE_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "accounts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addEmployerMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEmployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredEmployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementWithdraw",
    data: BytesLike
  ): Result;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [
    worker: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [worker: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    worker: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [
    worker: AddressLike,
    amount: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [worker: string, amount: bigint, penalty: bigint];
  export interface OutputObject {
    worker: string;
    amount: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployerMatchAddedEvent {
  export type InputTuple = [
    worker: AddressLike,
    employer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [worker: string, employer: string, amount: bigint];
  export interface OutputObject {
    worker: string;
    employer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployerRegisteredEvent {
  export type InputTuple = [employer: AddressLike];
  export type OutputTuple = [employer: string];
  export interface OutputObject {
    employer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetirementWithdrawalEvent {
  export type InputTuple = [worker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [worker: string, amount: bigint];
  export interface OutputObject {
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PensionVault extends BaseContract {
  connect(runner?: ContractRunner | null): PensionVault;
  waitForDeployment(): Promise<this>;

  interface: PensionVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGENCY_WITHDRAWAL_PENALTY: TypedContractMethod<[], [bigint], "view">;

  MAX_EMERGENCY_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  RETIREMENT_AGE_SECONDS: TypedContractMethod<[], [bigint], "view">;

  accounts: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalContributed: bigint;
        employerMatch: bigint;
        totalBalance: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  addEmployerMatch: TypedContractMethod<
    [worker: AddressLike],
    [void],
    "payable"
  >;

  contribute: TypedContractMethod<[], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAccount: TypedContractMethod<
    [worker: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalContributed: bigint;
        employerMatch: bigint;
        totalBalance: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerEmployer: TypedContractMethod<
    [employer: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredEmployers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  retirementWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGENCY_WITHDRAWAL_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EMERGENCY_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RETIREMENT_AGE_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accounts"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalContributed: bigint;
        employerMatch: bigint;
        totalBalance: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addEmployerMatch"
  ): TypedContractMethod<[worker: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccount"
  ): TypedContractMethod<
    [worker: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalContributed: bigint;
        employerMatch: bigint;
        totalBalance: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerEmployer"
  ): TypedContractMethod<[employer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredEmployers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "retirementWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "EmployerMatchAdded"
  ): TypedContractEvent<
    EmployerMatchAddedEvent.InputTuple,
    EmployerMatchAddedEvent.OutputTuple,
    EmployerMatchAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployerRegistered"
  ): TypedContractEvent<
    EmployerRegisteredEvent.InputTuple,
    EmployerRegisteredEvent.OutputTuple,
    EmployerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RetirementWithdrawal"
  ): TypedContractEvent<
    RetirementWithdrawalEvent.InputTuple,
    RetirementWithdrawalEvent.OutputTuple,
    RetirementWithdrawalEvent.OutputObject
  >;

  filters: {
    "ContributionMade(address,uint256,uint256)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "EmployerMatchAdded(address,address,uint256)": TypedContractEvent<
      EmployerMatchAddedEvent.InputTuple,
      EmployerMatchAddedEvent.OutputTuple,
      EmployerMatchAddedEvent.OutputObject
    >;
    EmployerMatchAdded: TypedContractEvent<
      EmployerMatchAddedEvent.InputTuple,
      EmployerMatchAddedEvent.OutputTuple,
      EmployerMatchAddedEvent.OutputObject
    >;

    "EmployerRegistered(address)": TypedContractEvent<
      EmployerRegisteredEvent.InputTuple,
      EmployerRegisteredEvent.OutputTuple,
      EmployerRegisteredEvent.OutputObject
    >;
    EmployerRegistered: TypedContractEvent<
      EmployerRegisteredEvent.InputTuple,
      EmployerRegisteredEvent.OutputTuple,
      EmployerRegisteredEvent.OutputObject
    >;

    "RetirementWithdrawal(address,uint256)": TypedContractEvent<
      RetirementWithdrawalEvent.InputTuple,
      RetirementWithdrawalEvent.OutputTuple,
      RetirementWithdrawalEvent.OutputObject
    >;
    RetirementWithdrawal: TypedContractEvent<
      RetirementWithdrawalEvent.InputTuple,
      RetirementWithdrawalEvent.OutputTuple,
      RetirementWithdrawalEvent.OutputObject
    >;
  };
}
